### ISSUE TITLE
[create_post] 홈 에서 작성하기 페이지로 이동 후, 뒤로가기 버튼 클릭 시 반응 없음

### ISSUE THREAD

**Issue by reeny404** [jonghoon7431/news-feed-project#13]

**Comment by hyowls** [comment]
리팩토링 하면서 커스텀 훅에서 navigate 리턴을 안해서 반응이 없었습니다 !
수정 완료했습니다 !

**Comment by reeny404** [comment]
수정 완료하셨다고 해서 이슈 닫겠... 아 맞다 테스트... 수업 끝나고 테스트하고 문제없으면 닫을께요
혹시 수정하신 pr link있으면 걸어주세요!

**Comment by reeny404** [comment]
dev에서 테스트 완료

**Comment by reeny404** [comment]
dev에서 테스트 완료
